- name: Install python gcc python 3
  ansible.builtin.dnf:
    name: "{{item}}"
    state: present
  loop:
       - python36
       - gcc
       - python3-devel
  
- name: download the zip files
  ansible.builtin.command: pip3.6 install -r requirements.txt
  args:
      chdir: /app